<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Notebook-1" data-toc-modified-id="Notebook-1-1">Notebook 1</a></span><ul class="toc-item"><li><span><a href="#1.1" data-toc-modified-id="1.1-1.1">1.1</a></span></li><li><span><a href="#1.2" data-toc-modified-id="1.2-1.2">1.2</a></span></li><li><span><a href="#1.3" data-toc-modified-id="1.3-1.3">1.3</a></span></li></ul></li><li><span><a href="#Notebook-2" data-toc-modified-id="Notebook-2-2">Notebook 2</a></span><ul class="toc-item"><li><span><a href="#2.1" data-toc-modified-id="2.1-2.1">2.1</a></span></li><li><span><a href="#2.2" data-toc-modified-id="2.2-2.2">2.2</a></span></li></ul></li><li><span><a href="#Notebook-3" data-toc-modified-id="Notebook-3-3">Notebook 3</a></span><ul class="toc-item"><li><span><a href="#3.1" data-toc-modified-id="3.1-3.1">3.1</a></span></li><li><span><a href="#3.2" data-toc-modified-id="3.2-3.2">3.2</a></span></li><li><span><a href="#3.3" data-toc-modified-id="3.3-3.3">3.3</a></span></li><li><span><a href="#3.4" data-toc-modified-id="3.4-3.4">3.4</a></span></li><li><span><a href="#3.5" data-toc-modified-id="3.5-3.5">3.5</a></span></li></ul></li><li><span><a href="#Notebook-4" data-toc-modified-id="Notebook-4-4">Notebook 4</a></span><ul class="toc-item"><li><span><a href="#4.1" data-toc-modified-id="4.1-4.1">4.1</a></span></li><li><span><a href="#4.2" data-toc-modified-id="4.2-4.2">4.2</a></span></li><li><span><a href="#4.3" data-toc-modified-id="4.3-4.3">4.3</a></span></li></ul></li><li><span><a href="#Notebook-5" data-toc-modified-id="Notebook-5-5">Notebook 5</a></span><ul class="toc-item"><li><span><a href="#5.1" data-toc-modified-id="5.1-5.1">5.1</a></span></li><li><span><a href="#5.2" data-toc-modified-id="5.2-5.2">5.2</a></span></li></ul></li><li><span><a href="#Notebook-6" data-toc-modified-id="Notebook-6-6">Notebook 6</a></span><ul class="toc-item"><li><span><a href="#6.1" data-toc-modified-id="6.1-6.1">6.1</a></span></li><li><span><a href="#6.2" data-toc-modified-id="6.2-6.2">6.2</a></span></li><li><span><a href="#6.3" data-toc-modified-id="6.3-6.3">6.3</a></span></li></ul></li><li><span><a href="#Notebook-7" data-toc-modified-id="Notebook-7-7">Notebook 7</a></span><ul class="toc-item"><li><span><a href="#7.1" data-toc-modified-id="7.1-7.1">7.1</a></span></li><li><span><a href="#7.2" data-toc-modified-id="7.2-7.2">7.2</a></span></li></ul></li><li><span><a href="#Notebook-8" data-toc-modified-id="Notebook-8-8">Notebook 8</a></span><ul class="toc-item"><li><span><a href="#8.1" data-toc-modified-id="8.1-8.1">8.1</a></span></li><li><span><a href="#8.2" data-toc-modified-id="8.2-8.2">8.2</a></span></li></ul></li><li><span><a href="#Notebook-9" data-toc-modified-id="Notebook-9-9">Notebook 9</a></span><ul class="toc-item"><li><span><a href="#9.1" data-toc-modified-id="9.1-9.1">9.1</a></span></li><li><span><a href="#9.2" data-toc-modified-id="9.2-9.2">9.2</a></span></li></ul></li><li><span><a href="#Notebook-10" data-toc-modified-id="Notebook-10-10">Notebook 10</a></span><ul class="toc-item"><li><span><a href="#10.1" data-toc-modified-id="10.1-10.1">10.1</a></span></li><li><span><a href="#10.2" data-toc-modified-id="10.2-10.2">10.2</a></span></li></ul></li><li><span><a href="#Notebook-11" data-toc-modified-id="Notebook-11-11">Notebook 11</a></span><ul class="toc-item"><li><span><a href="#11.1" data-toc-modified-id="11.1-11.1">11.1</a></span></li><li><span><a href="#11.2" data-toc-modified-id="11.2-11.2">11.2</a></span></li><li><span><a href="#11.3" data-toc-modified-id="11.3-11.3">11.3</a></span></li></ul></li></ul></div>

### Notebook 1
#### 1.1 
Look up docs for the `convert` function.

In [1]:
?convert

search: convert code_native @code_native



```
convert(T, x)
```

Convert `x` to a value of type `T`.

If `T` is an [`Integer`](@ref) type, an [`InexactError`](@ref) will be raised if `x` is not representable by `T`, for example if `x` is not integer-valued, or is outside the range supported by `T`.

# Examples

```jldoctest
julia> convert(Int, 3.0)
3

julia> convert(Int, 3.5)
ERROR: InexactError: Int64(3.5)
Stacktrace:
[...]
```

If `T` is a [`AbstractFloat`](@ref) or [`Rational`](@ref) type, then it will return the closest value to `x` representable by `T`.

```jldoctest
julia> x = 1/3
0.3333333333333333

julia> convert(Float32, x)
0.33333334f0

julia> convert(Rational{Int32}, x)
1//3

julia> convert(Rational{Int64}, x)
6004799503160661//18014398509481984
```

If `T` is a collection type and `x` a collection, the result of `convert(T, x)` may alias all or part of `x`.

```jldoctest
julia> x = Int[1, 2, 3];

julia> y = convert(Vector{Int}, x);

julia> y === x
true
```


#### 1.2 
Assign `365` to a variable named `days`. Convert `days` to a float.

In [2]:
days = 365
convert(Float64, days)

365.0

#### 1.3 
See what happens when you execute

```julia
convert(Int64, '1')
```
and

```julia
parse(Int64, '1')
```

What's the difference?

In [3]:
convert(Int64, "1")

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  ...

In [4]:
parse(Int64, "1")

1

### Notebook 2
#### 2.1 
Create a string that says "hi" 1000 times.

In [5]:
"hi"^1000

"hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihih

#### 2.2
Declare two variables

```julia
a = 3
b = 4
```
and use them to create two strings:
```julia
"3 + 4"
"7"
```

In [6]:
a = 3; b = 4

4

In [7]:
"$a + $b"

"3 + 4"

In [8]:
"$(a + b)"

"7"

### Notebook 3

#### 3.1 
Create an array, `a_ray`, with the following code:

```julia
a_ray = [1, 2, 3]
```

Add the number `4` to the end of this array and then remove it.

In [9]:
a_ray = [1, 2, 3]
push!(a_ray, 4)

4-element Vector{Int64}:
 1
 2
 3
 4

#### 3.2 
Try to add "Emergency" as key to `myphonebook` with the value `string(911)` with the following code
```julia
myphonebook["Emergency"] = 911
```

Why doesn't this work?

In [10]:
myphonebook = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String, String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [11]:
myphonebook["Emergency"] = 911
#= 

Julia inferred that`myphonebook` takes both keys and
values of type `String`. We see that myphonebook is a
`Dict{String,String} with 2 entries`. This means Julia
will not accept integers as values in myphonebook.

=#

LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type String
Closest candidates are:
  convert(::Type{String}, ::String) at essentials.jl:210
  convert(::Type{T}, ::T) where T<:AbstractString at strings/basic.jl:231
  convert(::Type{T}, ::AbstractString) where T<:AbstractString at strings/basic.jl:232
  ...

#### 3.3 
Create a new dictionary called `flexible_phonebook` that has Jenny's number stored as a string and Ghostbusters' number stored as an integer. 

In [12]:
flexible_phonebook = Dict("Jenny" => "867-5309", "Ghostbusters" => 5552368)

Dict{String, Any} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => 5552368

#### 3.4
Add the key "Emergency" with the value `911` (an integer) to `flexible_phonebook`.

In [13]:
flexible_phonebook["Emergency"] = 911

911

#### 3.5
Why can we add an integer as a value to `flexible_phonebook` but not `myphonebook`? How could we have initialized `myphonebook` so that it would accept integers or strings as values?

In [14]:
#= 

Julia inferred that`flexible_phonebook` takes values of 
type `Any`. Unlike myphonebook, flexible_phonebook is a 
`Dict{String,Any} with 2 entries`.

To avoid this, we could have initialized myphonebook a
an empty dictionary and added entries later. Or we
could have explicitly told Julia that we wanted a
dictionary that accepted objects of type `Any` as
values. See examples!
=#

myphonebook = Dict()

Dict{Any, Any}()

In [15]:
# Alternatively we could use a parametric type constructor to tell Julia explicitly
# what types we want to populate our dictionary with.
myphonebook = Dict{String, Any}("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String, Any} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

### Notebook 4

#### 4.1 
Write a loop that prints the squares of integers between 1 and 100.

In [16]:
for i in 1:100
   println(i^2) 
end

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000


#### 4.2

Add to the code above a bit to create a dictionary, `squares` that holds integers and their squares as key, value pairs such that

```julia
squares[10] == 100
```

In [17]:
squares = Dict()
for i in 1:100
   squares[i] = i^2 
end

#### 4.3 
Use an array comprehension to create an an array that stores the squares of all integers between 1 and 100.

In [18]:
[i^2 for i in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

### Notebook 5

#### 5.1 
Write a conditional statement that prints a number if the number is even and the string "odd" if the number is odd.

In [19]:
n = 3
if (n % 2) == 0
    println(n)
else
    println("odd")
end

odd


#### 5.2 
Rewrite the code from 5.1 using a ternary operator.

In [20]:
(n % 2) == 0 ? println(n) : println("odd") 

odd


### Notebook 6

#### 6.1 
Write a function that adds 1 to its input.

In [21]:
x -> x + 1

#3 (generic function with 1 method)

In [22]:
add1(x) = x + 1

add1 (generic function with 1 method)

#### 6.2 
Use `map` or `broadcast` to increment every element of matrix `A` by `1`.

In [23]:
map(x -> x + 1, A)

LoadError: UndefVarError: A not defined

In [24]:
broadcast(add1, A)

LoadError: UndefVarError: A not defined

#### 6.3 
Use the broadcast dot syntax to increment every element of matrix `A` by `1`.

In [25]:
add1.(A)

LoadError: UndefVarError: A not defined

In [26]:
A .+ 1

LoadError: UndefVarError: A not defined

### Notebook 7

#### 7.1 
Load the Primes package (source code at https://github.com/JuliaMath/Primes.jl).

In [27]:
#Pkg.add("Primes")
using Primes

LoadError: ArgumentError: Package Primes not found in current path:
- Run `import Pkg; Pkg.add("Primes")` to install the Primes package.


#### 7.2 
Verify that you can now use the function `primes` to grab all prime numbers under 1,000,000.

In [28]:
primes(1000000)

LoadError: UndefVarError: primes not defined

### Notebook 8

#### 8.1 
Given
```julia
x = -10:10
```
plot y vs. x for $y = x^2$.

In [29]:
using Plots; gr()
x = -10:10
y = x .^ 2
plot(x, y)

LoadError: ArgumentError: Package Plots not found in current path:
- Run `import Pkg; Pkg.add("Plots")` to install the Plots package.


In [30]:
plot(x -> x .^ 2, x)

LoadError: UndefVarError: plot not defined

#### 8.2 
Execute the following code

In [31]:
p1 = plot(x, x)
p2 = plot(x, x.^2)
p3 = plot(x, x.^3)
p4 = plot(x, x.^4)
plot(p1,p2,p3,p4,layout=(2,2),legend=false)

LoadError: UndefVarError: plot not defined

and then create a $4x1$ plot that uses `p1`, `p2`, `p3`, and `p4` as subplots.

In [32]:
p1 = plot(x, x)
p2 = plot(x, x.^2)
p3 = plot(x, x.^3)
p4 = plot(x, x.^4)
plot(p1,p2,p3,p4,layout=(4,1),legend=false)

LoadError: UndefVarError: plot not defined

### Notebook 9

#### 9.1

Extend the function `foo`, adding a method that takes only one input argument, which is of type `Bool`, and prints "foo with one boolean!"

In [33]:
foo(x::Bool) = println("foo with one boolean!")

foo (generic function with 1 method)

#### 9.2

Check that the method being dispatched when you execute 
```julia
foo(true)
```
is the one you wrote.

In [34]:
foo(true)

foo with one boolean!


In [35]:
@which foo(true)

foo(x::Bool) in Main at In[33]:1

### Notebook 10

#### 10.1
Take the outer product of a vector `v` with itself.

In [36]:
v = [1, 2, 3]
v * v'

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

#### 10.2
Take the inner product of a vector v with itself.

In [37]:
v' * v

14

### Notebook 11

#### 11.1

What are the eigenvalues of matrix A?

```
A =
[
 140   97   74  168  131
  97  106   89  131   36
  74   89  152  144   71
 168  131  144   54  142
 131   36   71  142   36
]
```

In [38]:
A =
[
 140   97   74  168  131
  97  106   89  131   36
  74   89  152  144   71
 168  131  144   54  142
 131   36   71  142   36
]

5×5 Matrix{Int64}:
 140   97   74  168  131
  97  106   89  131   36
  74   89  152  144   71
 168  131  144   54  142
 131   36   71  142   36

In [39]:
eigdec = eigfact(A)
eigdec[:values]

LoadError: UndefVarError: eigfact not defined

#### 11.2 
Create a `Diagonal` matrix from the eigenvalues of `A`.

In [40]:
Diagonal(eigdec[:values])

LoadError: UndefVarError: eigdec not defined

#### 11.3 
Create a `LowerTriangular` matrix from `A`.

In [41]:
LowerTriangular(A)

LoadError: UndefVarError: LowerTriangular not defined